Added training configs for all sizes
delphi-suite/delphi pull request #113
Opened 2024-04-09 17:48 UTC by SrGonao

(I messed up with the name of this branch. I tried renaming it but it didn't update)
I added a default mamba and llama 2 base (they are actually the same) and then the different llama 2 and mamba sizes.

2024-04-09 23:03 UTC, jettjaniak requested changes
Thank you!

**location**
for now configs should go to `src/delphi/static/configs/stories`

**naming**
we should either go with the full name that will end up on HF so
`stories-{llama2,mamba}-[num]{m,k}.json`
or just
`[num]{m,k}.json`
please note it should be `llama2` not `llama` and `m` not `M`

**inheritance**
you can specify all of the keys and values for `model_config` that are shared in the base configs, so e.g. `llama100k.json` should not specify `"model_class": "LlamaForCausalLM"`

@jaidhyani can we easily write a test that will check if all configs in the repo properly initialize?

@jannik-brinkmann please check if llama2 configs are correct

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/llama2/llama100k.json
> +    "eos_token_id": -2,
We probably should give the actual values from our tokenizer?

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/llama2/llama100k.json
> +    "pretraining_tp": 1,
what is this?

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/llama2/llama100k.json
> +    "tie_word_embeddings": false,
wait, this is not a standard setting for llama, is it?

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/mamba/mamba100k.json
> +    "pad_token_id": 0,
specify actual values, except we don't have pad token

2024-04-09 23:03 UTC, jettjaniak commented on src/llama2c
you somehow added a submodule that shouldn't be here

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_run.sh
we probably don't need this script in the repo

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/mamba/stories-mamba.json
> +        "gradient_accumulation_steps": 4,
why?

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/mamba/stories-mamba.json
> +    "output_dir": "output",
these should probably just take default values unless overridden via CLI argument?

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/mamba/stories-mamba.json
> +    },
Can we just not specify it? Not sure what the right approach here is

2024-04-09 23:03 UTC, jettjaniak commented on scripts/training_config_examples/mamba/mamba50M.json
> +    "CUBLAS_WORKSPACE_CONFIG=:4096:8": "MambaForCausalLM",
? :D

2024-04-12 10:35 UTC, SrGonao commented on scripts/training_config_examples/llama2/llama100k.json
> +    "tie_word_embeddings": false,
This was there from the Jai config, I just copy pasted. Maybe @jannik-brinkmann knows?

2024-04-12 10:36 UTC, SrGonao commented on scripts/training_config_examples/llama2/llama100k.json
> +    "pretraining_tp": 1,
the first 3 is how you define the specific parameters that we are using. I'm not sure I follow your question

2024-04-12 10:38 UTC, SrGonao commented on scripts/training_config_examples/mamba/stories-mamba.json
> +    "output_dir": "output",
I'm of the opinion that we want to have in the config all options that could be changed, but maybe this is the wrong way to view it.

2024-04-12 10:38 UTC, SrGonao commented on scripts/training_config_examples/mamba/stories-mamba.json
> +    },
Reposting from above: "I'm of the opinion that we want to have in the config all options that could be changed, but maybe this is the wrong way to view it"

2024-04-12 10:54 UTC, SrGonao commented
@jettjaniak, about inheritance, I'm not being able to have it working.
eg. if I have:
```
"model_config": {
        "model_class": "MambaForCausalLM",
        "vocab_size": 4096,
        "conv_kernel": 4,
        "expand": 2,
        "use_bias": false,
        "use_conv_bias": true,
        "hidden_act": "silu",
        "initializer_range": 0.1,
        "residual_in_fp32": true,
        "tie_word_embeddings": true
    }
```

in one mamba.json file and:
```"model_config": {
    "hidden_size": 952,
    "num_hidden_layers": 8
  }
```
in a 50M.json file
 and I run
`python scripts/run_training.py --config_files mamba.json --config_files 50M.json`
I get `KeyError: 'model_class'`

Could you verify it @jaidhyani ? I have changed all files to be like that either way

2024-04-12 19:22 UTC, jaidhyani commented
--config_files should be passed exactly once, with space-separated arguments if you want to pass multiple configs

2024-04-15 01:53 UTC, jettjaniak commented on scripts/training_config_examples/llama2/llama100k.json
> +    "pretraining_tp": 1,
pretraining_tp

2024-04-15 01:56 UTC, jettjaniak commented on scripts/training_config_examples/llama2/llama100k.json
> +    "eos_token_id": -2,
still relevant

2024-04-15 01:58 UTC, jettjaniak commented on scripts/training_config_examples/llama2/llama100k.json
> +    "tie_word_embeddings": false,
I think this is wrong

2024-04-15 02:00 UTC, jettjaniak commented on scripts/training_config_examples/mamba/mamba100k.json
> +    "pad_token_id": 0,
OK, now we're not setting bos/eos token id anywhere for mambas. Won't it cause any issues when using the models?

2024-04-15 02:18 UTC, jettjaniak commented on scripts/training_config_examples/llama2/llama100k.json
> +    "tie_word_embeddings": false,
or at least we were training with tied embeddings previously, and we probably computed the number of parameters assuming tied embeddings

2024-04-15 02:27 UTC, jettjaniak commented
TODOs
- [ ] set all the values instead of relying on defaults (we can find them here https://github.com/huggingface/transformers/tree/v4.39.3/src/transformers/models )
- [ ] decide on tie_word_embeddings
- [ ] verify number of parameters by initializing the models (maybe in a test?)
- [ ] make tests that will validate the configs
- [ ] figure out what to do with wandb_config, run_name, output_dir - should they be part of the config?

2024-04-16 23:26 UTC, jaidhyani commented
> TODOs
> 
> * [ ]  fix existing tests so they can access configs in new location

AFAIK there's not really a good way to include static files from outside of a package's root directory, by design. Basically all documentation on the subject assumes that static files are included in the project root - e.g. `src/` for us. I've just spent some time messing around with ways to get around this with MANIFEST.in or different setup.py options, couldn't get anything working.

2024-04-17 16:29 UTC, jettjaniak commented
can't we just determine the test file path and navigate from there to repo root?

2024-04-17 16:30 UTC, jettjaniak commented
oh, but that won't work if it's installed instead of cloned

2024-04-17 16:53 UTC, jettjaniak commented on scripts/training_config_examples/mamba/stories-mamba.json
> +    },
for now have a reasonable example config here that's commented

2024-04-17 16:53 UTC, jettjaniak commented on scripts/training_config_examples/mamba/stories-mamba.json
> +    "output_dir": "output",
these don't need to be defined, have sane defaults

2024-04-18 18:15 UTC, jettjaniak commented
gradient_accumulation_step should default to 0 in the code ❗

2024-04-18 18:32 UTC, jettjaniak commented
we need to look at all of these

```
    "run_name": " ",
    "output_dir": " ",
    "device": "auto",
    "eval_interval": 2000,
    "log_interval": 1,
    "eval_iters": 100,
    "eval_only": false,
    "always_save_checkpoint": false,
    "init_from": "scratch",
    "wandb_config": {
        "log": false,
        "project": " ",
        "entity": " "
    },
```
and change if needed

2024-04-18 18:32 UTC, jettjaniak commented
all of the model and training config were discussed and updated

2024-04-19 19:42 UTC, jaidhyani commented
#116 is a PR on top of this one to migrate static assets to the new top-level non-package path.

2024-04-19 23:17 UTC, jettjaniak commented
we need to find reasonable values for these
```
    "checkpoint_interval": -1000,
    "extra_checkpoint_iters": [
        -1000,
        -2000
    ],
    "log_interval": -1000,
```

2024-04-24 18:37 UTC, merged