Added static file folder
delphi-suite/delphi pull request #41
Opened 2024-02-19 21:47 UTC by menamerai

Is there a way to default to using the `delphi/static` folder instead of the `delphi` folder from the `from importlibs.resources import files` @jaidhyani ? In here I just join the path with `static` every time.

2024-02-19 23:23 UTC, jaidhyani commented
Sort of - `files` takes a module (or string-specifying-a-module) as an argument. So to make it point somewhere other than our package, we would need to give it a different argument. One thing we could do would be to add an `__init__.py` to the `static` dir, and then we could do `files(delphi.static)`. Either approach is fine, I think - your call.

But either way, you're right that we shouldn't require people to type that out each time. Let's add a `delphi/constants.py`, which for now can just contain `STATIC_ASSETS_DIR` definition.

2024-02-20 03:48 UTC, menamerai commented
@jaidhyani I added `__init__.py` to the directory, and added the constants file. How does it look now?

2024-02-21 08:25 UTC, jaidhyani approved these changes
This looks good to me. Minor follow-up tasks: 

1. We shouldn't necessarily force the output into the `STATIC_ASSETS_DIR`. Especially if the user specified a full path or a partial path with directory references, e.g.:
 
 `/home/me/Desktop/tokens.csv`
 `subdir/tokens.csv`
 
In the first case, the user has specified a full path, and we should use it. In the second, we can assume they're referring to a relative path from the current working directory, and we should output there.
 
We can get that behavior by calling `os.path.split` on the path arg, which returns a (head,tail) tuple. If `head` is empty, the user just passed a filename and we can probably throw it in the default output dir. If head isn't empty, we can call `os.path.expandvars` on the path arg to get the path we should output to.
 
2. We should also print the full path before writing, just to be explicit with the user about what file is being created and they know exactly where to look for it when it's done.

3. We should print out something when the export has completed successfully.

2024-02-21 13:06 UTC, joshuawe commented on setup.py
> +    package_data={"delphi.static": ["*"]},
Does this line mean:
1. There is *package_data* in `delphi/static` and
2. `["*"]` states that everything in `delphi/static` should be considered part of the package_data?

2024-02-21 13:08 UTC, joshuawe requested changes, later dismissed
This branch is behind *main* branch, so a rebase is necessary

2024-02-21 13:08 UTC, joshuawe commented on setup.py
> +    package_data={"delphi.static": ["*"]},
Does this line mean:
1. There is *package_data* in `delphi/static` and
2. `["*"]` states that everything in `delphi/static` should be considered part of the package_data?

2024-02-21 16:09 UTC, menamerai commented on setup.py
> +    package_data={"delphi.static": ["*"]},
I believe so, yes. You can also specify what kind of files get considered, like `"*.csv"`, `"*.pkl"`, but I'm leaving `"*"` for now because we're not sure what kind of format we'll be using for our data.

2024-02-21 16:25 UTC, menamerai commented
@joshuawe I rebased, not sure if I did that correctly. Does it look ok?

2024-02-23 17:08 UTC, jaidhyani approved these changes

2024-02-23 17:10 UTC, merged